import { useState } from "react";
import { Save, Download, Clock, Trash2, ChevronDown, ChevronUp } from "lucide-react";
import { toast } from "sonner";
import { type MarginInputs, type MarginResults, CURRENCIES, fmt } from "./calcEngine";

interface SavedCalc {
  id: string;
  savedAt: string;
  inputs: MarginInputs;
  results: MarginResults;
}

const LS_KEY = "agrismes_margin_calcs";

function loadSaved(): SavedCalc[] {
  try {
    return JSON.parse(localStorage.getItem(LS_KEY) ?? "[]");
  } catch {
    return [];
  }
}

function persistSaved(list: SavedCalc[]) {
  localStorage.setItem(LS_KEY, JSON.stringify(list));
}

interface Props {
  inputs: MarginInputs;
  results: MarginResults | null;
  aiSummary?: string;
  onLoad: (inputs: MarginInputs) => void;
}

export default function MarginSaveExport({ inputs, results, aiSummary, onLoad }: Props) {
  const [saved, setSaved] = useState<SavedCalc[]>(loadSaved);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [exporting, setExporting] = useState(false);

  const canSave = !!results && inputs.buyPrice > 0 && inputs.sellPrice > 0;

  const handleSave = () => {
    if (!results) return;
    const entry: SavedCalc = {
      id: crypto.randomUUID(),
      savedAt: new Date().toISOString(),
      inputs: { ...inputs, costs: inputs.costs.map((c) => ({ ...c })) },
      results: { ...results },
    };
    const next = [entry, ...saved].slice(0, 20);
    persistSaved(next);
    setSaved(next);
    toast.success("Calculation saved");
  };

  const handleDelete = (id: string) => {
    const next = saved.filter((s) => s.id !== id);
    persistSaved(next);
    setSaved(next);
    toast.success("Deleted");
  };

  const handleExportPDF = async () => {
    if (!results) return;
    setExporting(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const sym = CURRENCIES.find((c) => c.code === inputs.currency)?.symbol ?? "$";
      const W = 210;
      let y = 18;

      const section = (title: string) => {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 80, 200);
        doc.text(title, 14, y);
        y += 1;
        doc.setDrawColor(30, 80, 200);
        doc.setLineWidth(0.3);
        doc.line(14, y, W - 14, y);
        y += 6;
        doc.setTextColor(30, 30, 30);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
      };

      const row = (label: string, value: string) => {
        doc.setFont("helvetica", "bold");
        doc.text(label, 14, y);
        doc.setFont("helvetica", "normal");
        doc.text(value, 100, y);
        y += 6;
      };

      // Title
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(20, 20, 20);
      doc.text("Trade Margin Calculator", 14, y);
      y += 7;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(`Generated by AGRISMES  •  ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`, 14, y);
      y += 10;

      section("Trade Inputs");
      row("Commodity:", inputs.commodity || "—");
      row("Quantity:", `${inputs.quantity} ${inputs.unit}`);
      row("Currency:", inputs.currency);
      row("Buy Price:", `${sym}${inputs.buyPrice.toFixed(2)} / ${inputs.unit}`);
      row("Sell Price:", `${sym}${inputs.sellPrice.toFixed(2)} / ${inputs.unit}`);
      y += 2;

      if (inputs.costs.length > 0) {
        section("Additional Costs");
        inputs.costs.forEach((c) => {
          row(`${c.label || "Other"}:`, fmt(c.amount, sym));
        });
        row("Total Additional:", fmt(results.totalAdditionalCosts, sym));
        y += 2;
      }

      section("Calculation Results");
      row("Total Revenue:", fmt(results.totalRevenue, sym));
      row("Total Cost:", fmt(results.totalCost, sym));
      row("Gross Profit:", fmt(results.grossProfit, sym));
      row("Net Profit:", fmt(results.netProfit, sym));
      row("Gross Margin:", `${results.grossMarginPct.toFixed(1)}%`);
      row("Net Margin:", `${results.netMarginPct.toFixed(1)}%`);
      row("Markup:", `${results.markupPct.toFixed(1)}%`);
      row("ROI:", `${results.roi.toFixed(1)}%`);
      row("Break-Even Price:", fmt(results.breakEvenSellPrice, sym) + ` / ${inputs.unit}`);
      row("Margin Health:", results.health.toUpperCase());
      y += 4;

      if (aiSummary) {
        section("AI Analysis Summary");
        const lines = doc.splitTextToSize(
          aiSummary.replace(/#{1,4} /g, "").replace(/\*\*/g, ""),
          W - 28
        );
        const maxLines = Math.min(lines.length, 40);
        doc.text(lines.slice(0, maxLines), 14, y);
        y += maxLines * 5 + 4;
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(160, 160, 160);
      doc.text("AGRISMES Trade Intelligence — agrismes.com", 14, 290);
      doc.text("This is an estimate. Verify with your trade advisor.", W - 14, 290, { align: "right" });

      const filename = `agrismes-margin-${(inputs.commodity || "trade").replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.pdf`;
      doc.save(filename);
      toast.success("PDF exported");
    } catch (e: any) {
      toast.error("Export failed: " + (e.message || "unknown error"));
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="space-y-3">
      {/* Action buttons */}
      <div className="flex gap-2">
        <button
          onClick={handleSave}
          disabled={!canSave}
          className="flex-1 flex items-center justify-center gap-1.5 text-[13px] font-medium border border-border rounded-lg px-3 py-2.5 text-foreground hover:bg-accent disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          <Save className="w-3.5 h-3.5" />
          Save Calculation
        </button>
        <button
          onClick={handleExportPDF}
          disabled={!canSave || exporting}
          className="flex-1 flex items-center justify-center gap-1.5 text-[13px] font-medium bg-primary text-primary-foreground rounded-lg px-3 py-2.5 hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          {exporting ? "Exporting…" : "Export PDF"}
        </button>
      </div>

      {/* Saved history */}
      {saved.length > 0 && (
        <div className="rounded-xl border border-border overflow-hidden">
          <button
            onClick={() => setHistoryOpen((o) => !o)}
            className="w-full flex items-center justify-between px-4 py-3 text-[13px] font-medium text-foreground hover:bg-accent/40 transition-colors"
          >
            <div className="flex items-center gap-2">
              <Clock className="w-3.5 h-3.5 text-muted-foreground" />
              Saved Calculations ({saved.length})
            </div>
            {historyOpen ? <ChevronUp className="w-3.5 h-3.5 text-muted-foreground" /> : <ChevronDown className="w-3.5 h-3.5 text-muted-foreground" />}
          </button>

          {historyOpen && (
            <div className="border-t border-border divide-y divide-border max-h-60 overflow-y-auto">
              {saved.map((s) => (
                <div key={s.id} className="flex items-center gap-3 px-4 py-2.5 hover:bg-accent/30 transition-colors group">
                  <div className="flex-1 min-w-0">
                    <p className="text-[13px] font-medium text-foreground truncate">
                      {s.inputs.commodity || "Unnamed"} — {s.inputs.currency}
                      {s.inputs.quantity > 0 ? ` × ${s.inputs.quantity} ${s.inputs.unit}` : ""}
                    </p>
                    <p className="text-[11px] text-muted-foreground">
                      Net: {s.results.netMarginPct.toFixed(1)}% · {new Date(s.savedAt).toLocaleString()}
                    </p>
                  </div>
                  <button
                    onClick={() => onLoad(s.inputs)}
                    className="shrink-0 text-[11px] text-primary hover:underline opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    Load
                  </button>
                  <button
                    onClick={() => handleDelete(s.id)}
                    className="shrink-0 p-1 rounded text-muted-foreground hover:text-red-500 transition-colors opacity-0 group-hover:opacity-100"
                  >
                    <Trash2 className="w-3 h-3" />
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
