import jsPDF from 'jspdf';
import type { DocType } from './docTypes';
export function generatePDF(def:DocType,form:Record<string,string>,company:string,documentId:string){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});
  doc.setFillColor(15,26,20);doc.rect(0,0,210,28,'F');
  doc.setFillColor(22,163,74);doc.rect(0,28,210,1.5,'F');
  doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(13);
  doc.text('TradeDoc',15,12);
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(134,239,172);
  doc.text('docs.lenmacai.com  |  Lenmac Company Limited  |  BRELA 176550155',15,20);
  doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(255,255,255);
  doc.text(def.label.toUpperCase(),195,16,{align:'right'});
  let y=40;
  doc.setFillColor(249,250,251);doc.rect(15,y,180,8,'F');
  doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(107,114,128);
  doc.text('Issued by: '+(company||'Lenmac Company Limited'),18,y+5.5);
  doc.text('Generated: '+new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}),195,y+5.5,{align:'right'});
  y+=14;
  doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(107,114,128);
  doc.text('DOCUMENT ID',15,y);
  doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(17,24,39);
  doc.text(documentId,15,y+5);
  y+=14;
  for(const field of def.fields){
    const val=String(form[field.id]||'-');
    doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(107,114,128);
    doc.text(field.label.toUpperCase(),15,y);
    doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(17,24,39);
    const lines=doc.splitTextToSize(val,180);
    doc.text(lines,15,y+5);
    y+=5+lines.length*5+4;
    doc.setDrawColor(229,231,235);doc.setLineWidth(0.3);doc.line(15,y,195,y);y+=4;
    if(y>272){doc.addPage();doc.setFillColor(15,26,20);doc.rect(0,0,210,12,'F');doc.setTextColor(134,239,172);doc.setFontSize(8);doc.text('TradeDoc  |  '+def.label,15,8);y=20;}
  }
  const py=287;doc.setFillColor(243,244,246);doc.rect(0,py-3,210,13,'F');
  doc.setFontSize(7);doc.setTextColor(107,114,128);
  doc.text('Generated by TradeDoc  |  docs.lenmacai.com  |  Lenmac Company Limited',105,py+4,{align:'center'});
  doc.save(def.id+'_'+new Date().toISOString().split('T')[0]+'.pdf');
}
